server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personalized?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: redis
    port: 6379